name: Backend-Deploy

# 更换触发条件 在有Tag时才进行打包操作
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'
          cache: 'maven'

      - name: Build with Maven
        run: cd ./apartment-parent && mvn -DskipTests -B package --file pom.xml

      - name: Get version from tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker build
        id: buildX
        uses: docker/setup-buildx-action@v2

      - name: Build and push Gateway
        id: docker_build_gateway
        uses: docker/build-push-action@v4
        with:
          context: ./apartment-gateway
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/apartment-gateway:${{ steps.vars.outputs.tag }} 
            ${{ secrets.DOCKER_HUB_USERNAME }}/apartment-gateway:latest

      - name: Build and push Auth
        id: docker_build_auth
        uses: docker/build-push-action@v4
        with:
          context: ./apartment-auth/apartment-auth-api
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/apartment-auth-api:${{ steps.vars.outputs.tag }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/apartment-auth-api:latest

      - name: Build and push User
        id: docker_build_user
        uses: docker/build-push-action@v4
        with:
          context: ./apartment-user/apartment-user-api
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/apartment-user-api:${{ steps.vars.outputs.tag }}, 
            ${{ secrets.DOCKER_HUB_USERNAME }}/apartment-user-api:latest

#  deploy:
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
#      - name: Check out
#        uses: actions/checkout@v3
#
#      - name: 传输docker-compose到服务器
#        run: sshpass -p ${{secrets.REMOTE_PWD}} scp -r -o StrictHostKeyChecking=no ./docker-compose.yaml root@${{secrets.REMOTE_IP}}:/root/apartment-server
#
#      - name: 传输部署脚本到服务器
#        run: sshpass -p ${{secrets.REMOTE_PWD}} scp -r -o StrictHostKeyChecking=no ./deploy.sh root@${{secrets.REMOTE_IP}}:/root/apartment-server
#
#      - name: 授权并执行部署脚本
#        run: sshpass -p ${{secrets.REMOTE_PWD}} ssh -o StrictHostKeyChecking=no root@${{secrets.REMOTE_IP}} "chmod +x /root/apartment-server/deploy.sh && /root/apartment-server/deploy.sh"
